# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcul.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(409, 619)
        Form.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.qoshish = QtWidgets.QPushButton(Form)
        self.qoshish.setGeometry(QtCore.QRect(310, 480, 95, 65))
        button_style = (
    "QPushButton {"
    "background-color: rgb(72, 72, 72);"
    "color: rgb(255, 255, 255);"
    "border-radius: 7px;"
    "border: none;"
    "border: 2px solid blue;"
    "transition: all 0.2s;"
    "}"
    "QPushButton:hover {"
    "transform: scale(1.1);"
    "z-index: 1;"
    "}"
)
        button_style_tegma = (
    "QPushButton {"
    "    color: rgb(255, 255, 255);"
    "    border: none;"
    "    background-color: transparent;"
    "    transition: all 0.2s;"
    "}"
    "QPushButton:hover {"
    "    transform: scale(1.1);"
    "    z-index: 1;"
    "}"
)

        font = QtGui.QFont()
        font.setPointSize(15)
        self.qoshish.setFont(font)
        self.qoshish.setStyleSheet(button_style)
        self.qoshish.setObjectName("qoshish")
        self.tenglik = QtWidgets.QPushButton(Form)
        self.tenglik.setGeometry(QtCore.QRect(310, 550, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tenglik.setFont(font)
        self.tenglik.setStyleSheet(button_style)
        self.tenglik.setObjectName("tenglik")
        self.ayirish = QtWidgets.QPushButton(Form)
        self.ayirish.setGeometry(QtCore.QRect(310, 410, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ayirish.setFont(font)
        self.ayirish.setStyleSheet(button_style)
        self.ayirish.setObjectName("ayirish")
        self.foiz_chiqarish = QtWidgets.QPushButton(Form)
        self.foiz_chiqarish.setGeometry(QtCore.QRect(10, 200, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.foiz_chiqarish.setFont(font)
        self.foiz_chiqarish.setStyleSheet(button_style)
        self.foiz_chiqarish.setObjectName("foiz_chiqarish")
        self.boluv = QtWidgets.QPushButton(Form)
        self.boluv.setGeometry(QtCore.QRect(310, 270, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.boluv.setFont(font)
        self.boluv.setStyleSheet(button_style)
        self.boluv.setObjectName("boluv")
        self.bittalab_ochirish = QtWidgets.QPushButton(Form)
        self.bittalab_ochirish.setGeometry(QtCore.QRect(310, 200, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bittalab_ochirish.setFont(font)
        self.bittalab_ochirish.setStyleSheet(button_style)
        self.bittalab_ochirish.setObjectName("bittalab_ochirish")
        self.clear_del = QtWidgets.QPushButton(Form)
        self.clear_del.setGeometry(QtCore.QRect(110, 200, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_del.setFont(font)
        self.clear_del.setStyleSheet(button_style)
        self.clear_del.setObjectName("clear_del")
        self.clear = QtWidgets.QPushButton(Form)
        self.clear.setGeometry(QtCore.QRect(210, 200, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setStyleSheet(button_style)
        self.clear.setObjectName("clear")
        self.kopaytirish = QtWidgets.QPushButton(Form)
        self.kopaytirish.setGeometry(QtCore.QRect(310, 340, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.kopaytirish.setFont(font)
        self.kopaytirish.setStyleSheet(button_style)
        self.kopaytirish.setObjectName("kopaytirish")
        self.kvadratga_kotar = QtWidgets.QPushButton(Form)
        self.kvadratga_kotar.setGeometry(QtCore.QRect(110, 270, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kvadratga_kotar.setFont(font)
        self.kvadratga_kotar.setStyleSheet(button_style)
        self.kvadratga_kotar.setObjectName("kvadratga_kotar")
        self.btn_9 = QtWidgets.QPushButton(Form)
        self.btn_9.setGeometry(QtCore.QRect(210, 340, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet(button_style)
        self.btn_9.setObjectName("btn_9")
        self.btn_6 = QtWidgets.QPushButton(Form)
        self.btn_6.setGeometry(QtCore.QRect(210, 410, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet(button_style)
        self.btn_6.setObjectName("btn_6")
        self.btn_3 = QtWidgets.QPushButton(Form)
        self.btn_3.setGeometry(QtCore.QRect(210, 480, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet(button_style)
        self.btn_3.setObjectName("btn_3")
        self.vergul = QtWidgets.QPushButton(Form)
        self.vergul.setGeometry(QtCore.QRect(210, 550, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vergul.setFont(font)
        self.vergul.setStyleSheet(button_style)
        self.vergul.setObjectName("vergul")
        self.ildizdan_chiqar = QtWidgets.QPushButton(Form)
        self.ildizdan_chiqar.setGeometry(QtCore.QRect(210, 270, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ildizdan_chiqar.setFont(font)
        self.ildizdan_chiqar.setStyleSheet(button_style)
        self.ildizdan_chiqar.setObjectName("ildizdan_chiqar")
        self.btn_8 = QtWidgets.QPushButton(Form)
        self.btn_8.setGeometry(QtCore.QRect(110, 340, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet(button_style)
        self.btn_8.setObjectName("btn_8")
        self.btn_5 = QtWidgets.QPushButton(Form)
        self.btn_5.setGeometry(QtCore.QRect(110, 410, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet(button_style)
        self.btn_5.setObjectName("btn_5")
        self.btn_2 = QtWidgets.QPushButton(Form)
        self.btn_2.setGeometry(QtCore.QRect(110, 480, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet(button_style)
        self.btn_2.setObjectName("btn_2")
        self.btn_0 = QtWidgets.QPushButton(Form)
        self.btn_0.setGeometry(QtCore.QRect(110, 550, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet(button_style)
        self.btn_0.setObjectName("btn_0")
        self.taqsim_bolish = QtWidgets.QPushButton(Form)
        self.taqsim_bolish.setGeometry(QtCore.QRect(10, 270, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taqsim_bolish.setFont(font)
        self.taqsim_bolish.setStyleSheet(button_style)
        self.taqsim_bolish.setObjectName("taqsim_bolish")
        self.btn_7 = QtWidgets.QPushButton(Form)
        self.btn_7.setGeometry(QtCore.QRect(10, 340, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet(button_style)
        self.btn_7.setObjectName("btn_7")
        self.btn_4 = QtWidgets.QPushButton(Form)
        self.btn_4.setGeometry(QtCore.QRect(10, 410, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet(button_style)
        self.btn_4.setObjectName("btn_4")
        self.btn_1 = QtWidgets.QPushButton(Form)
        self.btn_1.setGeometry(QtCore.QRect(10, 480, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet(button_style)
        self.btn_1.setObjectName("btn_1")
        self.plus_minus = QtWidgets.QPushButton(Form)
        self.plus_minus.setGeometry(QtCore.QRect(10, 550, 95, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plus_minus.setFont(font)
        self.plus_minus.setStyleSheet(button_style)
        self.plus_minus.setObjectName("plus_minus")
        self.lebel_natija = QtWidgets.QLabel(Form)
        self.lebel_natija.setGeometry(QtCore.QRect(10, 60, 391, 81))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lebel_natija.setFont(font)
        self.lebel_natija.setStyleSheet("color: rgb(255, 255, 255);border: nome; background-color: transparent;")
        self.lebel_natija.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lebel_natija.setObjectName("lebel_natija")
        self.tegma_mc = QtWidgets.QPushButton(Form)
        self.tegma_mc.setGeometry(QtCore.QRect(10, 160, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_mc.setFont(font)
        self.tegma_mc.setStyleSheet(button_style_tegma)
        self.tegma_mc.setObjectName("tegma_mc")
        self.tegma_mc_2 = QtWidgets.QPushButton(Form)
        self.tegma_mc_2.setGeometry(QtCore.QRect(80, 160, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_mc_2.setFont(font)
        self.tegma_mc_2.setStyleSheet(button_style_tegma)
        self.tegma_mc_2.setObjectName("tegma_mc_2")
        self.tegma_m_plus = QtWidgets.QPushButton(Form)
        self.tegma_m_plus.setGeometry(QtCore.QRect(150, 160, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_m_plus.setFont(font)
        self.tegma_m_plus.setStyleSheet(button_style_tegma)
        self.tegma_m_plus.setObjectName("tegma_m_plus")
        self.tegma_m_minus = QtWidgets.QPushButton(Form)
        self.tegma_m_minus.setGeometry(QtCore.QRect(220, 160, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_m_minus.setFont(font)
        self.tegma_m_minus.setStyleSheet(button_style_tegma)
        self.tegma_m_minus.setObjectName("tegma_m_minus")
        self.tegma_ms = QtWidgets.QPushButton(Form)
        self.tegma_ms.setGeometry(QtCore.QRect(290, 160, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_ms.setFont(font)
        self.tegma_ms.setStyleSheet(button_style_tegma)
        self.tegma_ms.setObjectName("tegma_ms")
        self.tegma_m = QtWidgets.QPushButton(Form)
        self.tegma_m.setGeometry(QtCore.QRect(360, 160, 51, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tegma_m.setFont(font)
        self.tegma_m.setStyleSheet(button_style_tegma)
        self.tegma_m.setObjectName("tegma_m")
        self.tegma_standart = QtWidgets.QTextBrowser(Form)
        self.tegma_standart.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.tegma_standart.setStyleSheet("color: rgb(255, 255, 255);border: nome; background-color: transparent;")
        self.tegma_standart.setObjectName("tegma_standart")
        self.tegma_soat = QtWidgets.QPushButton(Form)
        self.tegma_soat.setGeometry(QtCore.QRect(330, 0, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tegma_soat.setFont(font)
        self.tegma_soat.setStyleSheet("color: rgb(255, 255, 255);border: nome; background-color: transparent;")
        self.tegma_soat.setObjectName("tegma_soat")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btn_0.clicked.connect(lambda: self.update_label('0'))
        self.btn_1.clicked.connect(lambda: self.update_label('1'))
        self.btn_2.clicked.connect(lambda: self.update_label('2'))
        self.btn_3.clicked.connect(lambda: self.update_label('3'))
        self.btn_4.clicked.connect(lambda: self.update_label('4'))
        self.btn_5.clicked.connect(lambda: self.update_label('5'))
        self.btn_6.clicked.connect(lambda: self.update_label('6'))
        self.btn_7.clicked.connect(lambda: self.update_label('7'))
        self.btn_8.clicked.connect(lambda: self.update_label('8'))
        self.btn_9.clicked.connect(lambda: self.update_label('9'))
        self.qoshish.clicked.connect(lambda: self.update_label('+'))
        self.ayirish.clicked.connect(lambda: self.update_label('-'))
        self.kopaytirish.clicked.connect(lambda: self.update_label('*'))
        self.boluv.clicked.connect(lambda: self.update_label('/'))
        self.vergul.clicked.connect(lambda: self.update_label(','))

        self.tenglik.clicked.connect(self.calculate_result)
        self.foiz_chiqarish.clicked.connect(self.foiz_chiqar)
        self.bittalab_ochirish.clicked.connect(self.bittalab_ochir)
        self.taqsim_bolish.clicked.connect(self.taqsim_bolishli)
        self.kvadratga_kotar.clicked.connect(self.kvadratga_kotar_funk)


        self.tenglik.clicked.connect(self.calculate_result)
        self.clear.clicked.connect(self.clear_label)

        self.tekshirish=False


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.qoshish.setText(_translate("Form", "+"))
        self.tenglik.setText(_translate("Form", "="))
        self.ayirish.setText(_translate("Form", "-"))
        self.foiz_chiqarish.setText(_translate("Form", "%"))
        self.boluv.setText(_translate("Form", "÷"))
        self.bittalab_ochirish.setText(_translate("Form", "⌫"))
        self.clear_del.setText(_translate("Form", "CE"))
        self.clear.setText(_translate("Form", "C"))
        self.kopaytirish.setText(_translate("Form", "x"))
        self.kvadratga_kotar.setText(_translate("Form", "x²"))
        self.btn_9.setText(_translate("Form", "9"))
        self.btn_6.setText(_translate("Form", "6"))
        self.btn_3.setText(_translate("Form", "3"))
        self.vergul.setText(_translate("Form", ","))
        self.ildizdan_chiqar.setText(_translate("Form", "√"))
        self.btn_8.setText(_translate("Form", "8"))
        self.btn_5.setText(_translate("Form", "5"))
        self.btn_2.setText(_translate("Form", "2"))
        self.btn_0.setText(_translate("Form", "0"))
        self.taqsim_bolish.setText(_translate("Form", "1/x"))
        self.btn_7.setText(_translate("Form", "7"))
        self.btn_4.setText(_translate("Form", "4"))
        self.btn_1.setText(_translate("Form", "1"))
        self.plus_minus.setText(_translate("Form", "+/-"))
        self.lebel_natija.setText(_translate("Form", ""))
        self.tegma_mc.setText(_translate("Form", "MC"))
        self.tegma_mc_2.setText(_translate("Form", "MR"))
        self.tegma_m_plus.setText(_translate("Form", "M+"))
        self.tegma_m_minus.setText(_translate("Form", "M-"))
        self.tegma_ms.setText(_translate("Form", "MS"))
        self.tegma_m.setText(_translate("Form", "M"))
        self.tegma_standart.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">☰    Standart</span></p></body></html>"))
        self.tegma_soat.setText(_translate("Form", "🕑"))

    def clear_label(self):
       self.lebel_natija.setText("")


    def update_label(self, number):
        current_text = self.lebel_natija.text()

        if current_text=="0" or self.tekshirish:
                self.lebel_natija.setText(number)
                self.tekshirish=False
        else:
             self.lebel_natija.setText(current_text + number)
    
    def calculate_result(self):
        try:
            result = eval(self.lebel_natija.text())
            self.lebel_natija.setText(str(result))
            self.tekshirish=True
        except Exception as e:
            self.lebel_natija.setText("Error")

#     def update_label(self, text):
#         current_text = self.lebel_natija.text()
#         if len(current_text) < 14:
#             self.lebel_natija.setText(current_text + text)

    def foiz_chiqar(self):
        foizda=eval(self.lebel_natija.text())
        self.lebel_natija.setText(str(foizda/100))
    
    def kvadratga_kotar_funk(self):
        self.soni = float(self.lebel_natija.text())
        self.lebel_natija.setText(str(self.soni ** 2))



    def bittalab_ochir(self):
        current_text = self.lebel_natija.text()
        if current_text:
           self.lebel_natija.setText(current_text[:-1])

    def taqsim_bolishli(self):
        try:
           current_value = float(self.lebel_natija.text())
           if current_value != 0:
               self.lebel_natija.setText(str(1/current_value)) 
           else:
               self.lebel_natija.setText("Error")
        except Exception as e:
           self.lebel_natija.setText("Error")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
